### ISSUE TITLE
Geocoder requirement analysis

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-geocoder#45]
Start by doing some user stories about the actual usage. After this, we will decide how to proceed with geocoding.

**Comment by tpievila** [comment]
Draft for comments


Käyttäjiä
=========

+++++++++++++++++++++++++++
Hanna, tarkka suunnittelija
+++++++++++++++++++++++++++
- Kouluttaa keskustan alueella
- Tuntee useimmat linjat, ei tunne kohteitaan
- Tiukka aikataulu
- Kohde on aina eri, lähtö/paluun määränpää aina sama
- Lähtöpaikka ei usein ole hakuhetken sijainti
- Hakee läppärillä
- Katsoo kohteen osoitteen ensin muualta, välillä paperilta välillä netistä
- Suunnittelee edeltävinä päivinä eri kellonajoille

Nopea kirjoittaja
-----------------
Hanna suunnittelee illalla kotonaan seuraavaa työpäiväänsä. Hänen kalenterissaan
on merkattuna koulutus Salomonkatu 2:ssa klo 13. Hän avaa Reittioppaan
läppärillään ja klikkaa etusivulla lähtö-kenttää, joka avaa listan edellisistä
kohteista. Toimiston osoite löytyy listasta, joten Hanna valitsee sen lähdöksi
klikkaamalla. Fokus siirtyy automaattisesti määränpääkenttään, johon Hanna
kirjoittaa nopeasti "Salomonkatu 2" ja painaa enteriä. Reittiopas hakee hänelle
reitin suoraan, koska kadun nimi on ainutlaatuinen pk-seudulla (ja koko
Suomessa). Reitin sivulla Hanna muuttaa kellonajan ja päivän oikeaksi.

Lähiaikataulut
--------------
Seuraavana päivänä, koulutuksen jälkeen, Hanna haluaa Salomonkatu 2:sta kotiinsa.
Hän on usein matkustanut Kampin kautta, joten hän tietää mikä linja on sopiva,
ja etsii sen kännykällään lähimpien pysäkkien tiedoista käyttämättä Reittihakua.

Olematon katu
-------------
Seuraavalla viikolla Hanna on saanut asiakkaan osoitteen työkaveriltaan
suullisesti. Osoite löytyy kalenterista, mutta on valitettavasti väärin:
Someronkatu 1, kun oikea osoite olisi Somerontie 1. Hän kirjoittaa osoitteen
määränpäähän ja painaa tottuneesti enteriä, mutta Reittiopas ei tee hakua, vaan
ilmoittaa väärästä kadunnimestä ja ehdottaa muita vaihtoehtoja (nykyinen
reittiopas antaa: Somerontie, Somerikkotie, Somerikkokuja, Somerikkopolku,
Somertie) samalla osoitenumerolla. Vaihtoehdot näkyvät myös kartalla, jonka
perusteella Hanna osaa valita ainoan Vallilassa olevan vaihtoehdon.

Olematon numero
---------------
Katu on olemassa, mutta numeroa ei ole.

Onko mahdollista, että käyttäjä oikeasti haluaa "osoitteeseen", jota ei
oikeastaan ole olemassa?

A) Kaikki olemassa olevat osoitteet on tiedossa, joten Reittiopas tarjoaa vain
niitä. Pitäisikö keskittää saman puolen numeroihin:
olematon numero 15 tarjoaisi 11, 13, 17, 19?

B) Osoitekanta ei ole kattava, joten numero interpoloidaan tiedetyistä
(eli jos on OSM + tieverkko, ei VRK:ta).

Katuja eri kaupungeissa
-----------------------
Haku "Kirkkokatu 2"

A) Numero löytyy monesta kaupungista -> ei suorita hakua enteristä vaan antaa
vaihtoehdot

B) Numero on vain yhdessä kaupungissa, vaikka katu onkin monessa -> tekee haun

Counterpoint: Nykyinen arpoo aina jonkin osoitteen oli se miten kaukaa haettu
tahansa, joka pitää monella klikillä korjata.

Monta rappua
------------
Eräänä päivänä Hanna tietää aikataulunsa tulevan olemaan erittäin kireä. Hän
syöttää määränpääksi (XXX Tuukalta ongelmatapaus). Osoitteessa on kuitenkin
kaksi eri rappua talon eri puolilla, joiden välillä siirtyminen kestää useamman
minuutin. Reittiopas näyttää Hannalle tarkemmat vaihtoehdot. Nähtyään miten
suuri ero reitissä on, Hanna tarkastaa vielä asiakkaan webbisivuilta missä
rapussa heidän toimistonsa tarkalleen on, ja valitsee sen määränpääksi.

Näkyykö OSMin kartassa rappu muutenkin aina? Onko se tarpeeksi huomattava /
selkeä, että käyttäjä miettii sen vaikutusta reittiin? Eri tarinat siitä
että kohdeosoitteen raput näkyvät korostettuina ja siitä että niihin tarjotaan
kävelyohjeet erikseen?

Osoite ruotsiksi
----------------
Asiakas on ruotsinkielinen ja on antanut osoitteensa ruotsiksi. Tämä toimii
silti reittioppaassa, vaikka Hannan oletuskieli onkin suomi.

Kutsuplus
---------
Reitti on hankala, näkyvillä on myös arvio kutsuplussan nopeudesta.


++++++++++++++++
Takeshi, turisti
++++++++++++++++
- ei tunne aluetta
- Alvar Aalto -fani
- Viettää pk-seudulla yhden päivän
- Haluaa käydä Aaltoyliopiston päärakennuksella, Dipolissa, Aallon ateljeella,
  Finlandia-talolla
- Tietää kohteen osoitteen ruotsinkielisestä esitteestä, ei tiedä sen olevan ruotsia
- Tulee lentokentältä, lähtee samana päivänä Tallinkin terminaalista
- Haluaa käydä syömässä
- Haluaa aina reitin juuri sillä hetkellä omasta sijainnistaan
- Hakee vain kännykällä
- Valmis maksamaan enemmän, jos se nopeuttaa tai vähentää kävelyä paljon

Aaltoon
-------
Takeshi saapuu aamulla Helsinki-Vantaalle. Hänellä on 12 tuntia aikaa tutustua
Alvar Aallon parhaisiin töihin ennenkuin hänen laivansa Tallinaan lähtee
Länsisatamasta. Takeshi avaa reittioppaan, joka tunnistaa ettei hänen selaimensa
hyväksy suomea ja valitsee automaattisesti käyttöliittymän kieleksi englannin.
Takeshin arkkitehtuuriopaskirja ei anna osoitteita, vaan ainoastaan rakennusten
nimiä, joten hän aloittaa kirjoittamalla tabletillaan määränpääksi "Aalto
university".

Missä olen
----------
Takeshi katsoo reitin, toteaa sen liian hankalaksi ja hitaaksi.
Haluaa tilata taksin, jota varten tarvitsee nykyisen sijaintinsa osoitteen.


++++++++++++++++++
Olavi, eläkeläinen
++++++++++++++++++
- Vanha, kirjoittaa hitaasti, kokee vaikeaksi osua näppäimiin
- Hakee tabletilla

Uimahallille
------------
Olavi haluaa uimaan, kirjoittaa "uima". Reittiopas tarjoaa vaihtoehtoina
"Uimaluoto", "Uimarannantie" ja "Uimarinpolku", sekä eri kategoriassa uimapalveluja
(mitkä nyt onkaan aakkosessa ensin uimahalleista, -rannoista jne.). Olavi kirjoittaa
hakuun vielä lisäksi "h":n, jolloin katunimiä ei enää löydy ja poi-kategoriaan
tulee uimahalleja aakkosjärjestyksessä, joista hän valitsee valikosta Espoonlahden
uimahallin.

Jyväskylään
-----------
Olavilla on lapsenlapsen kastajaiset Tikkakosken kirkolla, Jyväskylässä,
Kirkkokatu 16. Reittiopas ehdottaa osoitetta Helsingistä ja Espoosta, mutta
kirjoittamalla osoitteen perään "Jyväskylä" (pilkulla tai ilman pilkkua)
haku tarkentuu oikeaan paikkaan.


+++++++++++++++++
Saara, pyöräilijä
+++++++++++++++++
- Haluaa nähdä vertailuksi pyörämatkan
- Haluaa pyöräilyreitin, jossa on vähemmän mäkiä (muutettava sakkokerroin
  jokaisesta nousumetristä / jyrkkyydestä?)
- Haluaa karsia hausta pois tietyt linjat
- Haluaa nähdä kaupunkipyörät osana reittiä
- Haluaa pyörän kuljetuksen junassa osana reittiä


Käsittelemättömiä skenaarioita
==============================
- osoitteen kirjoitus ilman numeroa -> tarjoaa numeroita
- vanhat hakukohteet kaikilla laitteilla
- Maaseutu

  + "Hae koko maasta" -painike
  + Kaupunkien tunnistus katujen ohi, myös valitsematta "Hae koko maasta"
    vaihtoehtoina "keskusta" (piste OSMista) ja terminaalit
  + Miten valita koko maan haku ennen osoitteen kirjoittamista, jotta saisi
    prefixin perusteella ehdotuksia?

- Ei PK kaupunkiseudulla (Tampere, Turku, Oulu). Haku tunnistaa sijainnin ja
  1) antaa vain paikallisen kaupungin tulokset vai 2) antaa paikallisen
  pk-seudun lisäksi
- Jos osoitehaku ei anna tulosta pk-seudulla, mutta antaa koko maasta,
  tulisiko näitä ehdottaa vaikka koko maan hakua ei ole eksplisiittiesti valittu?
- Uimahalli-tarina on sekä lipas että palvelukartta, tarvitaan erikseen tarinat
- Typot, onko parempi valita paras match vai antaa käyttäjän valita vaikka
  muutosetäisyys olisi pieni?

**Comment by samuliheljo** [comment]
Approved! Next up: Work with PO.
