### ISSUE TITLE
Geocoder API

### ISSUE THREAD

**Issue by samuliheljo** [HSLdevcom/digitransit-geocoder#6]
| Endpoint | Description |
| --- | --- |
| /address/&lt;city&gt;/&lt;streetname&gt; | Return all housenumbers with locations on the given street, in given city. |
| /address/&lt;city&gt;/&lt;streetname&gt;/&lt;housenumber&gt; | Return location for given housenumber in given street and city. |
| /suggest/&lt;search term&gt;[?city=Cityname[&city=Anothercity]] | Return all kinds of objects with given term anywhere in the name. Streetnames are returned per each city and including number of addresses in the street. All other objects include location. Every type is in a separate list with a field name in result object. Also returns streetnames with Levenshtein distance of two. Query parameter city can be specified one or more times to limit suggestions to within those cities. |
| /reverse/&lt;lat&gt;,&lt;lon&gt;[?zoom=8] | Return nearest address for given WGS84 coordinates. If given zoom level is under 8, then returns municipality, not an address. |
| /interpolate/&lt;streetname&gt;/&lt;housenumber&gt; | Return an estimated location for an address interpolated from road network data. |
| /meta | Return metadata about the API. Currently the date when the data was last updated in "updated" field in ISO 8601 format. |

**Comment by tpievila** [comment]
Search API requires feedback at this point.

**Comment by samuliheljo** [comment]
Geocoding API changes (Ensured from Ville that these are needed in order to build solid UI):

- /search/{string}
  - Must return addresses in ascending order
  - Must return stop in ascending stop_code 
  - Must return all other results in alphabetically ascending order
  - Every result must contain location information.
  - Must work with capital addresses
  - Must work with mml tieosoitteet
  - Must work with mml kuntarajat
  - Must work with OSM POI
  - Must work with GTFS stops
  - Must work with liikuntapaikat
  - Must work with pääkaupunkiseudun palvelukartta

- /search/{string}/{number}
  - Must return location information

- /suggest/{string}
  - Must work with capital addresses
  - Must work with mml tieosoitteet
  - Must work with mml kuntarajat
  - Must work with OSM POI
  - Must work with GTFS stops
  - Must work with liikuntapaikat
  - Must work with pääkaupunkiseudun palvelukartta
  - All results should be returned like now, in separate lists
  - Must return some location for all items (Address = Address 1)
    - For addresses "Address" is same as "Address 1"
    - This can be implemented so that we precalculate locations during import or if fast enough do it in API
    - This enables us to move map when autocomplete cursor moves
    - This enables us to route to address just by street name, without making many requests from client

- /suggest/{string}/{number}
  - Must return hits from all cities with given number

- /metadata
  - Must return metadata about api
  - Must return date of datasources

- Error Handling 
  - Do not show stack traces for 404 request, show "not found" text
  - Do not show stack trace when error occurs

**Comment by hukka** [comment]
Yeah, I suppose I wasn't going to get this finished at this point ;)
